[workspace]
members = []

[workspace.dependencies]
derive-where = "1"
impls = "1"
pub-fields = "0.1"

[package]
name = "shame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-where.workspace = true
pub-fields.workspace = true

[dev-dependencies]
impls.workspace = true
